# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Default
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: CmdLine@2
      displayName: Build
      inputs:
        script: dotnet build

    - task: CmdLine@2
      displayName: Test
      inputs:
        script: dotnet test

    # Build Docker image
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        repository: donlyone/myproject   # ← CHANGE WAS HERE
        tags: |
          latest

    # Login to Docker Hub
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dockerhub-connection

    # Push Docker image
    - task: Docker@2
      displayName: Push Docker image
      inputs:
        command: push
        repository: donlyone/myproject   # ← AND HERE
        tags: |
          latest
